In [ ]:
print("Hello ! I am excited to learn PyTorch")

Hello ! I am excited to learn PyTorch


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


## Introduction to tensors

### Creating Tensors
PyTorch Tensors are created using torch.tensor() -> https://docs.pytorch.org/docs/stable/generated/torch.tensor.html

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#Got tensor back as python int
scalar.item()

7

In [ ]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#Matrix
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [ ]:
TENSOR1 = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]],
                        [[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR1

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]],

        [[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR1.shape

torch.Size([2, 3, 3])

In [ ]:
TENSOR2 = torch.tensor([[[[1,2,3],
                         [4,5,6],
                         [7,8,9]]],
                       [[[10,11,12],
                         [13,14,15],
                         [16,17,18]]],
                       [[[19,20,21],
                         [22,23,24],
                         [25,26,27]]]])
TENSOR2

tensor([[[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9]]],


        [[[10, 11, 12],
          [13, 14, 15],
          [16, 17, 18]]],


        [[[19, 20, 21],
          [22, 23, 24],
          [25, 26, 27]]]])

In [ ]:
TENSOR2.shape

torch.Size([3, 1, 3, 3])

In [ ]:
TENSOR2.ndim

4

### Random Tensors

Why random tensors?

Random tensors are important becuse the way many neurak networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

'start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers

https://docs.pytorch.org/docs/stable/generated/torch.rand.html

In [ ]:
# create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.1170, 0.2538, 0.7498, 0.0882],
        [0.3091, 0.7442, 0.4718, 0.7179],
        [0.2338, 0.7004, 0.9906, 0.8282]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (224,224,3)) #height,width,color channel(r, g, b)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [ ]:
# Create a Tensor of all zeros
zeros = torch.zeros(size = (3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

## Creating a Range of tensors and tensors-like

In [ ]:
# use torch.range()
one_to_ten = torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#creating tensors like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Datatypes

** Note ** Tensor datatypes is one of the 3 big issues with pytorch and deep learning
   1. Tensors not right datatype
   2. Tensors not right shape
   3. Tensors not the right device

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype = None, # what datatype is the tensor (e.g. float32 or float16)
                               device = None, # what device is your tensor on
                               requires_grad = False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.half)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor.dtype

torch.float16

In [ ]:
float_64_tensor = float_32_tensor.type(torch.double)
float_64_tensor

tensor([3., 6., 9.], dtype=torch.float64)

In [ ]:
float_64_tensor.dtype


torch.float64

### Getting Information from tensors

     1. Tensors not right datatype - to do get datatype from a tensor, can use tensor.dtype
     2.tensors not right shape - to get shape fom a tensor,can use tensor.shape
     3. Tensors not on the right device - to get right device from a tensor, we can use tensor.device

In [ ]:
#Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.8478, 0.0868, 0.1585, 0.4730],
        [0.1146, 0.7103, 0.7749, 0.7082],
        [0.6590, 0.2894, 0.2772, 0.7385]])

In [ ]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor:{some_tensor.dtype}")
print(f"Shape of tensor:{some_tensor.size}")
print(f"Right device of tensor:{some_tensor.device}")

tensor([[0.8478, 0.0868, 0.1585, 0.4730],
        [0.1146, 0.7103, 0.7749, 0.7082],
        [0.6590, 0.2894, 0.2772, 0.7385]])
Datatype of tensor:torch.float32
Shape of tensor:<built-in method size of Tensor object at 0x7998ccec4410>
Right device of tensor:cpu


### Manipulating Tensors(tensor operations)
Tensor operations include:
   *Addition
   *Substraction
   *Multiplication
   *Element wise Multiplication
   *Division
   *matrix

In [ ]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [ ]:
# Add 10 to the tensor

tensor+10

tensor([11, 12, 13])

In [ ]:
#multiply tensor by 10
tensor*10

tensor([10, 20, 30])

In [ ]:
# Divide tensor by 10
tensor/10

tensor([0.1000, 0.2000, 0.3000])

In [ ]:
#subtract 10
tensor - 10

tensor([-9, -8, -7])

###Matrix Multiplication
     1. Element wise Multiplication
     2. Matrix multiplication(dot product)

There are two main rules to that permforming matrix multilication needs to satisfy:

     1. The **inner dimensions** must match:

     *  '(3,2)@(3,2)' won't work
     *  '(2,3)@(3,2)' will work
     *  '(3,2)@(2,3)' will work


In [ ]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: user 1.17 ms, sys: 0 ns, total: 1.17 ms
Wall time: 2.69 ms


In [ ]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 115 µs, sys: 18 µs, total: 133 µs
Wall time: 403 µs


tensor(14)

###One of the most common errors in Deep Learning : Shape errors

In [ ]:
# Shapes for matrix multiplication

tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
#torch.mm() is the same as torch.matmul
torch.matmul(tensor_A,tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape,tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issue, we can mnaipulate the shape of out tensors using a **transpose**

A **transpose** switches the axes or dimensions of a given tensor.

In [ ]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [ ]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape}, (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output: \n")
output = torch.matmul(tensor_A,tensor_B.T)
print(output)
print(f"\nOutput shape : {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]), (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output: 

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape : torch.Size([3, 3])


## Finding the min,max,mean,sum,etc(tensor aggregation)

In [ ]:
#Create a tensor
x = torch.arange(0,100,10)
x


tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find the min
torch.min(x),x.min()

(tensor(0), tensor(0))

In [ ]:
# Find the max
torch.max(x),x.max()
x.dtype

torch.int64

In [ ]:
# Find the mean
torch.mean(x.type(torch.float32))

tensor(45.)

#Finding the positional mean and max

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
x.argmin()

tensor(0)

In [ ]:
x[0]

tensor(0)

In [ ]:
x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(90)

In [ ]:
#Let's create a tensor
import torch
x = torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
#Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping -  reshapes an input tensor to a defined shape
*View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* stacking - combine multiple tensors on top of each other(vstack) or side by side(hstack)
* Squueeze -  removes all '1' dimensions to a target tensor
* Unsqueeze - add a '1' dimension to a target tenor
* Permute - Return a view of the input with dimensions permuted(swapped) in a certain way


In [ ]:
# Let's create a tensor
import torch
x = torch.arange(1.,9.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8.]), torch.Size([8]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(4,2)
x_reshaped, x_reshaped.shape

(tensor([[1., 2.],
         [3., 4.],
         [5., 6.],
         [7., 8.]]),
 torch.Size([4, 2]))

In [ ]:
y = torch.arange(1.,13.)
y,y.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [ ]:
y_reshaped = y.reshape(6,2)
y_reshaped,y_reshaped.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.],
         [11., 12.]]),
 torch.Size([6, 2]))

In [ ]:
y_reshaped = y.reshape(4, 3)
y_reshaped,y_reshaped.shape

(tensor([[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.],
         [10., 11., 12.]]),
 torch.Size([4, 3]))

In [ ]:
y_reshaped = y.reshape(2,6)
y_reshaped,y_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.],
         [ 7.,  8.,  9., 10., 11., 12.]]),
 torch.Size([2, 6]))

In [ ]:
y_reshaped = y.reshape(3, 4)
y_reshaped,y_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]]),
 torch.Size([3, 4]))

In [ ]:
#change the view
z = x.view(1,8)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8.]]), torch.Size([1, 8]))

In [ ]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8.]))

In [ ]:
# stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.]])

In [ ]:
# torch.squeeze()= removes all dimensions form target tensors
print(f"Previous tensir: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshapedd
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensir: tensor([[5., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
Previous shape: torch.Size([4, 2])

New tensor: tensor([[5., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
New shape: torch.Size([4, 2])


In [ ]:
#torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim(dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

#add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([[5., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
Previous shape: torch.Size([4, 2])

New tensor: tensor([[[5., 2.],
         [3., 4.],
         [5., 6.],
         [7., 8.]]])
New shape: torch.Size([1, 4, 2])


In [ ]:
# torch.permute() = rearranges the dimension of  target tensor in a specified

tensor([[5., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])

In [ ]:
x_reshaped.squeeze().shape

torch.Size([4, 2])

In [ ]:
#torch.permute - rearranges the dimension of a target tensor in a specified order
import torch
x_original = torch.rand(size=(224,224,3))

#permute the original tensor to rearrange the axis (or dim) order

x_permuted = x_original.permute(2,0,1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [ ]:
x_original

tensor([[[0.6375, 0.8816, 0.8523],
         [0.9042, 0.0783, 0.1954],
         [0.3059, 0.2558, 0.8441],
         ...,
         [0.2571, 0.0029, 0.7960],
         [0.5961, 0.2722, 0.0027],
         [0.9032, 0.7710, 0.0117]],

        [[0.5856, 0.2637, 0.7573],
         [0.4230, 0.3771, 0.7557],
         [0.6327, 0.9502, 0.3383],
         ...,
         [0.1161, 0.0499, 0.1323],
         [0.3545, 0.0384, 0.5195],
         [0.1337, 0.2046, 0.0283]],

        [[0.0445, 0.1238, 0.0179],
         [0.0556, 0.8791, 0.2897],
         [0.9213, 0.6683, 0.7222],
         ...,
         [0.4010, 0.5987, 0.4487],
         [0.0202, 0.3123, 0.0646],
         [0.8341, 0.5701, 0.9801]],

        ...,

        [[0.2151, 0.7044, 0.4707],
         [0.9341, 0.0301, 0.5420],
         [0.9443, 0.8502, 0.5649],
         ...,
         [0.5772, 0.2308, 0.2082],
         [0.5088, 0.3486, 0.3062],
         [0.9710, 0.5315, 0.5362]],

        [[0.6004, 0.0821, 0.9739],
         [0.6877, 0.9143, 0.2720],
         [0.

In [ ]:
x_original[0, :, :]

tensor([[6.3747e-01, 8.8157e-01, 8.5230e-01],
        [9.0416e-01, 7.8300e-02, 1.9543e-01],
        [3.0585e-01, 2.5575e-01, 8.4409e-01],
        [5.3689e-01, 2.0652e-01, 5.5675e-01],
        [7.1824e-01, 1.6526e-01, 5.9933e-01],
        [6.5493e-01, 6.7481e-01, 6.9482e-01],
        [5.0851e-01, 6.7136e-01, 8.2672e-01],
        [5.5252e-01, 9.8896e-01, 2.5140e-01],
        [9.4990e-01, 3.7101e-01, 1.1286e-01],
        [5.5164e-01, 9.6847e-02, 5.3532e-01],
        [6.6452e-01, 6.2815e-01, 4.9251e-01],
        [3.5294e-01, 6.0569e-01, 3.2677e-01],
        [9.3334e-01, 6.8461e-02, 2.1601e-01],
        [3.6846e-01, 1.3754e-01, 2.3151e-01],
        [3.8249e-01, 6.9283e-01, 7.6214e-01],
        [5.5224e-01, 1.0693e-01, 4.1452e-01],
        [1.2335e-02, 8.7585e-01, 9.0961e-01],
        [9.1830e-01, 3.8991e-01, 4.8803e-01],
        [3.3234e-02, 3.4145e-01, 2.8930e-01],
        [4.8567e-01, 8.3363e-01, 9.3414e-01],
        [7.0416e-01, 6.4108e-01, 9.6779e-01],
        [2.8590e-02, 9.2188e-02, 4

In [ ]:
x_original[0,0,0] = 63747
x_original[0,0,0], x_permuted[0,0,0]

In [ ]:
#create a tensor

import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
 #Let's index on our new tensor
 x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
#let's index on the middle bracket(dim = 1)
x[0][0]

tensor([1, 2, 3])

In [ ]:
# Let's index on the most inner bracket
x[0][2][0]

tensor(7)

In [ ]:
x[0][2][2]

tensor(9)

In [ ]:
# You can also use":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
x[:, :, 0]

tensor([[1, 4, 7]])

In [ ]:
x[:, 0, 0]

tensor([1])

In [ ]:
x[:, 0, 1]

tensor([2])

In [ ]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [ ]:
# Get index 0 of oth and 1st dimension and all values of 2nd dimension

x[0, 0, :]

tensor([1, 2, 3])

In [ ]:
# Index on x to return 9
print(x[:,2,2])

# Index on x to return 3,6,9
print(x[:, :, 2])

tensor([9])
tensor([[3, 6, 9]])


In [ ]:
x[:,2,2]

tensor([9])

## PyTorch tensors a NumPy

NumPy i a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interacct with it .

* Data in NumPy , Want in PyTorch tensor-> torch.from_numpy(ndarray)

* PyTorch tensor ->NumPy-> torch.Tensor.numpy()

In [ ]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor


(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
array.dtype

dtype('float64')

In [ ]:
torch.arange(1.0,8.0).dtype

torch.float32

In [ ]:
# change the value of array, what will this do to 'tensor?

array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
# Tensor to numpuy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor,numpy_tensor


(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
numpy_tensor.dtype

dtype('float32')

In [ ]:
# Change the tensor, what happens to 'numpy_tensor'?

tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

##PyTorch Reproducibility(trying to take random out of random)

In short how a neural network learns:

start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again..

To reduce the randomness in neural network and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.

In [ ]:
torch.rand(3,3)

tensor([[0.4905, 0.9551, 0.9539],
        [0.5340, 0.7804, 0.3997],
        [0.4981, 0.5816, 0.9024]])

In [ ]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.1334, 0.4415, 0.1295, 0.0570],
        [0.7583, 0.7836, 0.2144, 0.3546],
        [0.0686, 0.6229, 0.0395, 0.6743]])
tensor([[0.9329, 0.0648, 0.4249, 0.3534],
        [0.0296, 0.1956, 0.7588, 0.1288],
        [0.5835, 0.9058, 0.1113, 0.4681]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + nvidia harrdware + pytorch woring behind the scenes to make everything hunky

### 1. Getting a GPU

# Easisest - Use Google colab free GPU (Options to upgrade as well)
#use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU
# Use cloud computing - GCP, AWS, AZURE, thes services allow you to rent computers on the cloud to access them

#For 2, 3 Ptorch + GPU drivers(CUDA) takes a little bit of setting up

In [ ]:
!nvidia-smi

Wed May 21 06:16:02 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   45C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

### 2. check for GPU access with PYTORCH

In [ ]:
# check for GPU access with Pytorch

import torch
torch.cuda.is_available()

True

In [ ]:
# Setup device agnostic code

device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count number of devices
torch.cuda.device_count()

1

For PyTorch since it's capable of running compute on the GPU or CPU , it's best practice to setup device agnostic code:

E.g. run on GPU if available, else default to cpu

In [ ]:

device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

## 3. Putting tensors(and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU reuslts in faster computations.

In [ ]:
# Create a tensor() default on the CPU

tensor = torch.tensor([1,2,3], device='cpu')

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Mocve tensor to GPU if available

tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [ ]:
# if tensor is on GPU , can't transform it to numpy
#tensor_on_gpu.numpy()


In [ ]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU

tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
## Exercises & Extra Curriculum
